#!/bin/bash

alias db="docker-compose build"
alias dup="docker-compose up"
alias dbnocache="docker-compose build --no-cache"
alias run="uvicorn apiluizalabs.main:app --port 8989 --reload"
alias testv="pytest -v"
alias testcov="pytest --cov=apiluizalabs"
alias testcovhtml="pytest --cov=apiluizalabs --cov-report=html"
